config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  
  root to: 'events#index'

  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]
    
    post :show, on: :member
  end

  resources :users, only: %i[show edit update]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user])
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, only: %i[show edit update destroy]

  after_action :verify_authorized, only: %i[show edit update destroy]

  def index
    @events = Event.all
  end

  def show
    begin
      authorize @event
    rescue Pundit::NotAuthorizedError
      if params[:pincode].present?
        flash.now[:alert] = I18n.t('controllers.events.wrong_pincode')
      end
      
      render 'password_form'
    end

    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @event

    @event.destroy
    redirect_to events_url, notice:I18n.t('controllers.events.destroyed')
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class='col-sm-6 col-md-4'>
  <div class='card thumbnail'>

    <%= content_tag 'div', '', class: 'event-background',
      style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>

    <div class='thumbnail-inner event-info-inner'>
      <div class='card-body'>
        <div class='event-description'>
        <div class='card-title'>
          <h3><%= link_to event.title, event_path(event) %></h3>
        </div>
        <div class='card-text'>
          <h3><small><%= l event.datetime, format: :short %></small></h3>
        </div>
          <div class='mt-2'><%= event.address %></div>
          <div>
            <% event.visitors.each do |user| %>
              <%= image_tag user_avatar_thumb(user), title: user.name, class: 'circle' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <%= render partial: 'partials/form_errors', locals: {model: event} %>

  <div class='mb-3'>
    <%= form.label :title, class: 'mb-1' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class='mb-3'>
    <%= form.label :address, class: 'mb-1'  %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class='mb-3'>
    <%= form.label :datetime, class: 'mb-1'  %>
    <p><%= form.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class='mb-3'>
    <%= form.label :description, class: 'mb-1'  %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class='mb-3'>
    <%= form.label :pincode, class: 'mb-1' %>
    <%= form.text_field :pincode, class: 'form-control' %>
  </div>

  <div class='actions mb-3'>
    <%= form.submit t('buttons.save'), class: 'btn btn-primary' %>
    <%= link_to t('buttons.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= I18n.t('headings.event_editing') %></h1>

<div class='row'>
  <div class='col-md-6 mt-2'>
    <%= render 'form', event: @event %>
    
    <%= link_to t('buttons.event.delete'), event_path(@event), method: :delete,
      data: { confirm: t('are_you_sure') }, class: 'mt-1 btn btn-danger' %>
  </div>
</div>

app/views/events/index.html.erb
<h1><%= I18n.t('headings.events') %></h1>

<div class='my-4'>
  <%= link_to t('buttons.event.create'), new_event_path, class: 'btn btn-success' %>
</div>

<div class='row mb-2'>
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1><%= I18n.t('headings.new_event') %></h1>

<div class='row'>
  <div class='col-md-6 mt-2'>
    <%= render 'form', event: @event %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1><%= I18n.t('headings.pincode_needed') %></h1>

<%= form_tag('', method: 'post') do |f| %>
  <div class='mb-3'>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  
    <%= label_tag :pincode, t('pincode'), class: 'mb-1' %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>
  
  <div class='mb-3'>
    <%= submit_tag t('buttons.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to t('buttons.to_root'), root_path %>

app/views/events/show.html.erb
<div>
  <div class='event-info row'>
    <div class='col-md-12'>
      <%= content_tag 'div', '',
        class: 'event-background',
        style: "background-image: url(#{asset_path('event.jpg')})"
      %>

      <div class='event-info-inner row p-3'>
        <div class='col-md-6'>
          <div class='event-description d-flex flex-column gap-2'>
            <h1><%= @event.title %></h1>
            <h4><%= l @event.datetime, format: :short %></h4>
            <h4><small><%= link_to @event.address,
                "https://yandex.ru/maps/?text=#{@event.address}" %></small></h4>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class='my-2'>
              <%= link_to t('buttons.event.edit'), edit_event_path(@event),
                class: 'btn btn-warning' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-8'>
      <div class='event-photos'>
        <div class='event-photos-gallery mb-3'>
          <h4><%= I18n.t('headings.photos') %></h4>
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>
        <% if user_signed_in? %>
          <div class='event-photo-form'>
            <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
          </div>
        <% end %>
      </div>
      <div class='event-comments mt-2'>
        <h4><%= I18n.t('headings.comments') %></h4>
        <%= render partial: 'comments/form', locals: {comment: @new_comment || @event.comments.build} %>
        
        <div class='mt-2'>
          <%= render partial: 'comments/comment', collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>
    <div class='col-md-4'>
      <div class='event-owner'>
        <h4><%= I18n.t('headings.organized') %></h4>
          <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <% if @event.subscriptions.except(@new_subscription).any? %>
        <div class='event-subscriptions'>
          <h4><%= I18n.t('headings.will_attend') %></h4>
          <div>
            <p>
            <%= render partial: 'subscriptions/subscription',
              collection: @event.subscriptions.except(@new_subscription) %>
            </p>
          </div>
        </div>
      <% end %>

      <div>
        <h4><%= I18n.t('headings.address') %></h4>
        <div id='map' data-address='<%= @event.address %>' class='map'></div>
      <div>

      <% unless current_user_can_edit?(@event) %>
        <div class='event-subscription-form'>
          <h4><%= I18n.t('headings.join') %></h4>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
              subscription: @new_subscription || @event.subscriptions.build } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'map' %>
<%= javascript_pack_tag 'lightbox' %>